### ISSUE TITLE
Increase Render Distance in-game.

### ISSUE THREAD

**Issue by Dave12328** [MarbleItUp/MIULevelCreationKit#11]
After Scaling things like the SpiralSquareMapped so large in order for it to fit the entire level, It vanishes cause the render distance is too low. To fix this issue I'd like to request that the render distance be turned up so we can use some of these assets that are larger than usual.

**Comment by Blueteak** [comment]
Game-specific changes are outside the scope of this GitHub project, the discord suggestion channel is better for this type of request due to its potential game performance impact across the board
