### ISSUE TITLE
Testing level with non-PC version?

### ISSUE THREAD

**Issue by PiotrMi** [MarbleItUp/MIULevelCreationKit#5]
Hi,

I bought Marble it up for Switch. Is there a possibility to playtest my own levels without having to buy the game for PC again? I tried playing in the Editor but it doesn't seem to work. All I got when in Play Mode was a preview view of the track.

Unity version: 2018.2.0f2

**Comment by Blueteak** [comment]
Currently we have not found a way to load files onto device via SD card for self-testing

**Comment by bengarney** [comment]
Marking resolved as we are not taking an action on this right now.
