### ISSUE TITLE
Custom items?

### ISSUE THREAD

**Issue by IanSloat** [MarbleItUp/MIULevelCreationKit#9]
Is there a way to create custom items and other level assets or is the game scripted to recognize only empty placeholder item assets from unity? For example, I was thinking of attempting to port items from the old marble blast games like the gravity modifier and duct fan. Is this possible?

**Comment by bengarney** [comment]
Dynamic items are not portable right now, unfortunately - they tie deeply into physics and gameplay logic. We will release more level elements in later updates.
